"""add organization owner

Revision ID: 245a5f8b158a
Revises: 861f15993e94
Create Date: 2026-09-06 16:58:48.906139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245a5f8b158a'
down_revision: Union[str, Sequence[str], None] = '861f15993e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_organization_created_by'), 'organization', ['created_by'], unique=False)
    op.execute("""
        UPDATE organization o
        SET created_by = (
        SELECT m.user_id FROM organization_member m 
        WHERE m.organization_id = o.id AND m.role = 'admin'
        ORDER BY m.id LIMIT 1
        )
        WHERE created_by is NULL
""")
    op.create_foreign_key(None, 'organization', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_index(op.f('ix_organization_created_by'), table_name='organization')
    op.drop_column('organization', 'created_by')
    # ### end Alembic commands ###
