"""add issue and issue_activity

Revision ID: 80e5be903bb9
Revises: a01c1c1882aa
Create Date: 2026-09-02 22:39:55.893751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e5be903bb9'
down_revision: Union[str, Sequence[str], None] = 'a01c1c1882aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_key', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
    sa.Column('issue_type', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'issue_key', name='unique_issue_key_per_project')
    )
    op.create_index(op.f('ix_issue_assignee_id'), 'issue', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_issue_created_at'), 'issue', ['created_at'], unique=False)
    op.create_index(op.f('ix_issue_issue_key'), 'issue', ['issue_key'], unique=False)
    op.create_index(op.f('ix_issue_priority'), 'issue', ['priority'], unique=False)
    op.create_index(op.f('ix_issue_project_id'), 'issue', ['project_id'], unique=False)
    op.create_index(op.f('ix_issue_reporter_id'), 'issue', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_issue_status'), 'issue', ['status'], unique=False)
    op.create_table('issue_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(length=100), nullable=True),
    sa.Column('new_value', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_activity_issue_id'), 'issue_activity', ['issue_id'], unique=False)
    op.create_index(op.f('ix_issue_activity_user_id'), 'issue_activity', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_activity_user_id'), table_name='issue_activity')
    op.drop_index(op.f('ix_issue_activity_issue_id'), table_name='issue_activity')
    op.drop_table('issue_activity')
    op.drop_index(op.f('ix_issue_status'), table_name='issue')
    op.drop_index(op.f('ix_issue_reporter_id'), table_name='issue')
    op.drop_index(op.f('ix_issue_project_id'), table_name='issue')
    op.drop_index(op.f('ix_issue_priority'), table_name='issue')
    op.drop_index(op.f('ix_issue_issue_key'), table_name='issue')
    op.drop_index(op.f('ix_issue_created_at'), table_name='issue')
    op.drop_index(op.f('ix_issue_assignee_id'), table_name='issue')
    op.drop_table('issue')
    # ### end Alembic commands ###
