"""scope issue_key uniqueness to project

Revision ID: 89555e166529
Revises: fedd4049ac48
Create Date: 2026-08-14 16:37:58.060972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89555e166529'
down_revision: Union[str, Sequence[str], None] = 'fedd4049ac48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('issue_issue_key_key'), 'issue', type_='unique')
    op.create_index(op.f('ix_issue_issue_key'), 'issue', ['issue_key'], unique=False)
    op.create_unique_constraint('unique_issue_key_per_project', 'issue', ['project_id', 'issue_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_issue_key_per_project', 'issue', type_='unique')
    op.drop_index(op.f('ix_issue_issue_key'), table_name='issue')
    op.create_unique_constraint(op.f('issue_issue_key_key'), 'issue', ['issue_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
